<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubCategory2_leftmenu_CLP</name>
   <tag></tag>
   <elementGuidId>a346897c-0f51-4528-95da-5371955d0188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='nav-sub-link-leftMenu']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>860a2c5d-26d7-4262-8c5d-d4314b6727e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678034367066</value>
      <webElementGuid>7d8ab6e4-8076-41be-a00d-2ab9d226d0d2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
