<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_month_AM</name>
   <tag></tag>
   <elementGuidId>96743ba9-e375-412a-b9fc-5157a55064bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthSelectorLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;idLabel__Month&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>764161af-e6e8-4cf5-a8c7-ec6ce8b1d82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-select__native-control</value>
      <webElementGuid>55a36b60-5391-4563-b1ee-8ac1d54e853e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthSelectorLabel</value>
      <webElementGuid>5a1693f6-cc5f-4e4f-b551-58d7bf2b9304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EneFebMarAbrMayJunJulAgoSepOctNovDic</value>
      <webElementGuid>a5b682f2-d32f-4b3f-bad0-946e53d70bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCreateAccount&quot;)/div[@class=&quot;row m-wrapDate mt-3&quot;]/div[@class=&quot;col-4 middleDatePicker select-datePicker-space&quot;]/div[@class=&quot;mdc-ripple-upgraded mdc-select--focused mdc-ripple-upgraded--background-focused&quot;]/div[@class=&quot;mdc-select mdc-select--outlined mdc-select--focused&quot;]/select[@id=&quot;monthSelectorLabel&quot;]</value>
      <webElementGuid>d06a7cea-9854-41ec-bb38-80e10866c38e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='monthSelectorLabel']</value>
      <webElementGuid>54487587-35db-45ea-8699-4209f1c6f3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCreateAccount']/div[9]/div[2]/div/div/select</value>
      <webElementGuid>d72faae1-5d9b-4d8a-8c6c-56c3795fcbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Día'])[1]/following::select[1]</value>
      <webElementGuid>ee7803aa-73d7-483f-907b-db992d4e938c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de Nacimiento'])[1]/following::select[2]</value>
      <webElementGuid>4fa81850-f7aa-4556-a7f7-96ad77699235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mes'])[1]/preceding::select[1]</value>
      <webElementGuid>b33cf77e-b3aa-49bd-a41b-836b9e5b45c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año'])[1]/preceding::select[2]</value>
      <webElementGuid>841bd696-1225-4372-b3e0-836469f97531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>e988f44f-819f-425f-9737-38c1a4f20958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'monthSelectorLabel' and (text() = 'EneFebMarAbrMayJunJulAgoSepOctNovDic' or . = 'EneFebMarAbrMayJunJulAgoSepOctNovDic')]</value>
      <webElementGuid>fa88ca8b-de3f-4826-a9af-91fd78640dab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
