<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L2CategoryInFlyout_HP</name>
   <tag></tag>
   <elementGuidId>59073cec-a5db-48fb-a859-c1bfa1e59e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-desktop__categoryTitle.categoryLevel-2undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='CAT610036']//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8aa27b14-71c2-4e6b-afcd-e874f029d6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-desktop__categoryTitle categoryLevel-2undefined</value>
      <webElementGuid>0ae232ed-26a5-4e3c-8d09-89b0f12ae144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ropa</value>
      <webElementGuid>e4dd16ef-e38e-4937-b11a-de17ef3c35b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CAT610036&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-top&quot;]/div[@class=&quot;col-lg-8 category-menu&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 pb-3&quot;]/a[@class=&quot;a-desktop__categoryTitle categoryLevel-2undefined&quot;]</value>
      <webElementGuid>8babc71b-4e97-41c7-a957-53ea780c73be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CAT610036']/div/div[2]/div/div/div/a</value>
      <webElementGuid>0e539e99-afd4-4a3c-9522-4a2d4eb1ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ropa')]</value>
      <webElementGuid>3f39a1a4-34ef-4d1a-9c1a-138bd65f3d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[2]/following::a[1]</value>
      <webElementGuid>5d9e29b0-d083-4910-b69e-b6c3a0615eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[1]/following::a[2]</value>
      <webElementGuid>89a6d86a-fe6a-423c-b051-2dba77a17212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chamarras Abrigos &amp; Chalecos'])[1]/preceding::a[1]</value>
      <webElementGuid>edd22c26-c366-434d-8171-10a985618ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suéteres &amp; Sudaderas'])[1]/preceding::a[2]</value>
      <webElementGuid>88e75fb5-3ce0-47d0-93ed-581fe546c48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ropa']/parent::*</value>
      <webElementGuid>a6910901-185a-433e-bbe9-d6bef022dc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>0b7b74d8-c173-4d5c-9225-88d2b9f4e69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ropa' or . = 'Ropa')]</value>
      <webElementGuid>697f8c46-9c4b-42bd-a8fe-ffa6dae7bf5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
