<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Editar</name>
   <tag></tag>
   <elementGuidId>e4c51c6c-b167-45fb-8697-e6ccb5f81bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[5]/div/div/div/div[2]/div/div/div[2]/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>599fa915-7fc2-40f3-93b8-87e3b8ce2f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-menuMotion__link dropdown-item ripple-motion ripple-one-line</value>
      <webElementGuid>5257f5f9-466d-497a-a0b1-b182b79808c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>af833dbc-38e6-48ac-9815-77f1257d2948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#AirTime-removeCellphone</value>
      <webElementGuid>c9946c3e-3d23-40cc-818f-6b367e1376db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>a5dede78-2271-4f96-aebf-16b1d661f269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent cards-main-content&quot;]/div[@class=&quot;o-myAccount__cards -default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 false&quot;]/div[@class=&quot;m-box m-cardBox credit-cards  opc_cardadded&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1 p-0&quot;]/div[@class=&quot;menuMotion dropleft&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;a-menuMotion__link dropdown-item ripple-motion ripple-one-line&quot;]</value>
      <webElementGuid>5ec6fc01-afe3-4f0f-9b76-c41331f80563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[5]/div/div/div/div[2]/div/div/div[2]/div/div/a[2]</value>
      <webElementGuid>31eb865f-99d9-411e-8240-f9deb6fa58b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Editar')])[2]</value>
      <webElementGuid>6aad091d-586f-4e80-81b6-1730a46e0856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar como predeterminada'])[1]/following::a[1]</value>
      <webElementGuid>7566ec2f-32d7-4f56-91cb-fd59f0d6e373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/following::a[4]</value>
      <webElementGuid>8253af15-672c-48c7-bfec-3ec3cec17740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/preceding::a[1]</value>
      <webElementGuid>c216cc67-d470-451a-a683-647bf433768d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar como predeterminada'])[2]/preceding::a[3]</value>
      <webElementGuid>90bef550-f6a1-4248-a4a4-4fbb3a8ed08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/a[2]</value>
      <webElementGuid>fba89ced-48e2-4a2b-bdb3-5120f8002fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>df35baa7-bf95-4b8d-8b25-3c8abd2f36e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
