<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eliminar</name>
   <tag></tag>
   <elementGuidId>59215226-efaf-48fb-98d1-b13b1ee8bc67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[5]/div/div/div/div[2]/div/div/div[2]/div/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>766fcf42-5324-4c45-a2e8-1f6dadec1530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-menuMotion__link dropdown-item ripple-motion ripple-one-line</value>
      <webElementGuid>f39fd09a-29cb-451c-96b5-da42ca721f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0a8ffbfd-3014-48de-ac13-e55379485401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#AirTime-removeCellphone</value>
      <webElementGuid>bbf3b3d1-ee2b-430e-9c31-a6b4cf251656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>c17647a2-b140-4cc9-b307-cc80813d55c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent cards-main-content&quot;]/div[@class=&quot;o-myAccount__cards -default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 false&quot;]/div[@class=&quot;m-box m-cardBox credit-cards  opc_cardadded&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1 p-0&quot;]/div[@class=&quot;menuMotion dropleft&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;a-menuMotion__link dropdown-item ripple-motion ripple-one-line&quot;]</value>
      <webElementGuid>7a9d5126-5bda-4e1e-b65c-c3490c1bedd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[5]/div/div/div/div[2]/div/div/div[2]/div/div/a[3]</value>
      <webElementGuid>f4d20bda-9cb9-4ac7-b779-e9a86120e5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eliminar')]</value>
      <webElementGuid>15fc7812-6839-443a-a1bc-47068b639c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[2]/following::a[1]</value>
      <webElementGuid>4d066f2f-74e8-49ee-b90d-d2f889c72745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar como predeterminada'])[1]/following::a[2]</value>
      <webElementGuid>11231ab5-d4a5-4f54-8f2a-d2788c582e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar como predeterminada'])[2]/preceding::a[2]</value>
      <webElementGuid>3c3ed784-b6fb-4507-bcde-704203c61c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/preceding::a[3]</value>
      <webElementGuid>50214e32-f3ff-47c9-8c67-da2aaab9cfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar']/parent::*</value>
      <webElementGuid>2fb4a956-8d88-4c8c-9c03-11fe8238be49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>c4f354e3-94c9-499f-9bfe-f1d5176fb4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>57c7294b-abbe-4d45-9a9e-28120d22a0dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
