<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agregar tarjeta</name>
   <tag></tag>
   <elementGuidId>fdb00fa7-d908-4e56-8db1-907aa3169b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loggedInCC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loggedInCC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6aa50ced-f115-491d-a7e0-72015b05eebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary d-none d-lg-block</value>
      <webElementGuid>13095869-46d1-417b-bb1e-056d4a1bb612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loggedInCC</value>
      <webElementGuid>7d012cea-db20-40f1-8910-08e4bfe1a59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-condition</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3811c504-294d-4f8f-8a25-bd6e348fa283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar tarjeta</value>
      <webElementGuid>d080d33e-e317-4bfc-bb43-2e8f25944f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loggedInCC&quot;)</value>
      <webElementGuid>027522d0-7023-489e-ada4-0616f601eca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='loggedInCC']</value>
      <webElementGuid>ff5ae599-993e-474b-b5c1-117bfeda88b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[5]/div/div/div[2]/div/button</value>
      <webElementGuid>845a7e53-2070-43a8-ad63-e13ec55df138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[5]/following::button[1]</value>
      <webElementGuid>a82980c7-811d-4b44-8696-4a9838382f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[6]/following::button[1]</value>
      <webElementGuid>27bc63fb-9e74-4661-b9cf-791e6f3e17b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar tarjeta'])[2]/preceding::button[1]</value>
      <webElementGuid>22b21931-1fcb-4a90-99b5-90a67afe0e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar tarjeta'])[1]/preceding::button[2]</value>
      <webElementGuid>f629b2c6-717e-41fd-b281-bf9ee0502bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar tarjeta']/parent::*</value>
      <webElementGuid>b8e092ec-c846-4ba0-8535-194caebec170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>c60c4a03-7e4d-4e2f-827f-c4cf40952baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'loggedInCC' and (text() = 'Agregar tarjeta' or . = 'Agregar tarjeta')]</value>
      <webElementGuid>a059393d-076c-4b36-94fd-07b055be1ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
