<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Editar_icon-more_vert</name>
   <tag></tag>
   <elementGuidId>8d7417fc-fd20-4143-b459-bdd1d8a7f27f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='address1']/i)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a73a3986-fb4f-4478-9e3e-f546f5e269ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-more_vert</value>
      <webElementGuid>a452b12f-9dec-4345-b36c-bfc2710395cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent cards-main-content&quot;]/div[@class=&quot;o-myAccount__cards -default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 false&quot;]/div[@class=&quot;m-box m-cardBox credit-cards  opc_cardadded&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1 p-0&quot;]/div[@class=&quot;menuMotion dropleft&quot;]/a[@id=&quot;address1&quot;]/i[@class=&quot;icon-more_vert&quot;]</value>
      <webElementGuid>a8fadc02-55ba-43a5-9336-e9b90a448aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='address1']/i)[2]</value>
      <webElementGuid>c18920c2-058c-4358-b5ec-7c6720d4e36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a/i</value>
      <webElementGuid>a9535138-1198-4572-ba48-a96bf55a6964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
