<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usar el nombre de mi cuenta_fullNameUser</name>
   <tag></tag>
   <elementGuidId>e4eed6c9-91fc-400b-b83c-332fa42e1757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullNameUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullNameUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>775c0fa8-e82c-4a15-a16c-46482e07dbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullNameUser</value>
      <webElementGuid>d531f2c9-0d5b-46bc-a711-cb436f2b979b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input a-material__input</value>
      <webElementGuid>21155c42-671a-4d04-9aa0-68e94eafe722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e1ac73c-27dd-4580-95ac-900aa2b44d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92b88916-7063-4b02-85d6-2ab838e21861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullNameUser</value>
      <webElementGuid>9c2473bd-fe2b-4e84-8f4c-ad229036eb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>onlyText</value>
      <webElementGuid>2821c89d-4dd5-4c3a-b427-f4f7c5d541f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3aa5cd0f-2b04-4761-8cb8-f387115ccafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4df18e89-6d2e-4d68-9a92-3e60041dc319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullNameUser&quot;)</value>
      <webElementGuid>9e8193d9-b3bc-4cc4-ae41-9bcc600a9718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullNameUser']</value>
      <webElementGuid>82387174-943d-4346-8389-4e72347e0987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[4]/div/div/div[5]/div/div/div/input</value>
      <webElementGuid>dabe628f-9c38-4ba9-a82c-2e422d04daa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>b30d9963-3644-40df-a2b4-8e88c98e907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fullNameUser' and @type = 'text' and @name = 'fullNameUser']</value>
      <webElementGuid>43c3b83c-ddcf-4bf5-87c7-a34fb1747fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
