<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actualizar</name>
   <tag></tag>
   <elementGuidId>96fef1a0-37cc-4582-b9a9-be50a734f7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--primary.test</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3daa908d-7749-42d6-aedb-304e20d2e3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary test</value>
      <webElementGuid>68522b14-6de2-4523-bb58-932b38c345ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar</value>
      <webElementGuid>df499b7b-ede6-4582-ba54-c3de1395ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateDataPersonal&quot;)/div[@class=&quot;m-box-form__content--my__account col-12 col-lg-5 px-4 ml-lg-2 pb-lg-3&quot;]/div[@class=&quot;m-form-buttons&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 order-1 order-lg-1 col-lg&quot;]/button[@class=&quot;a-btn a-btn--primary test&quot;]</value>
      <webElementGuid>9759126b-2a08-4723-af11-6a06abfc246e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type=''])[2]</value>
      <webElementGuid>a84955f4-78a6-4987-baf7-b76f441aa7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdateDataPersonal']/div[3]/div[11]/div/div[2]/button</value>
      <webElementGuid>ee598fe4-0c54-4810-8b5e-fc84fea33e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>f420d6d6-8dff-437b-8d5e-89a95028cc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[1]/following::button[2]</value>
      <webElementGuid>5d51c14b-9d0a-41bd-9a9a-560f4feb98b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte al cliente'])[1]/preceding::button[1]</value>
      <webElementGuid>69dd9751-1c64-4a73-9a20-73c8bdf294aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facturación'])[1]/preceding::button[1]</value>
      <webElementGuid>3c1e630c-a847-4ff3-965c-5ca8bc81d85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar']/parent::*</value>
      <webElementGuid>4b71060c-7b03-4c6a-92db-e6043c573108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/button</value>
      <webElementGuid>b1088185-04e0-4317-bc01-5822493462b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Actualizar' or . = 'Actualizar')]</value>
      <webElementGuid>d26b7194-0228-4d5d-8117-783a3f85d1c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
