<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo Electrnico_firstName</name>
   <tag></tag>
   <elementGuidId>132605bc-4502-4464-b2cc-9e8b0a4c4744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-update__name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aed0274-c0ef-44d3-a5e6-12076df07086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-update__name</value>
      <webElementGuid>15eadae7-1a7b-467c-998d-161eaee41e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input a-material__input</value>
      <webElementGuid>3ca4df82-dd0b-4288-9945-000a07cc055b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0521233-4569-4191-a572-54b5b0c167c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f47f74b6-98dd-4e80-8290-0ec24327f7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>6abc4292-5f6d-4353-a047-e67523d6d115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>textWithSpecialCharsNoQ</value>
      <webElementGuid>bfce4c13-d960-4dcd-b9fc-04484d4299c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d03d7b28-4ee3-4cb6-9be0-9096f597420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>harish</value>
      <webElementGuid>6158f8df-e2cc-4ba7-bea4-d271891339d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-update__name&quot;)</value>
      <webElementGuid>c6390a14-ab5d-4d54-85e8-7cb31fcfd0a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-update__name']</value>
      <webElementGuid>eb597ba8-7f82-4c9d-a645-71907ce842f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdateDataPersonal']/div[3]/div[3]/div/input</value>
      <webElementGuid>29ed0f0e-7564-4d97-8260-25cacf5b7c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e1187475-5a52-459e-a88b-6b75012a33d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-update__name' and @type = 'text' and @name = 'firstName']</value>
      <webElementGuid>6f0f3f5a-4825-48a7-8706-01dc7b4803a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
